// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcphjzyqmvzhekalcwkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcGhqenlxbXZ6aGVrYWxjd2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDMwNDYsImV4cCI6MjA1NTE3OTA0Nn0.dqD3x39VInQW3glT74cPqUrnG9nPMk0p0QwYlpAoUSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);